# Generated by Django 2.0 on 2019-09-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190827_1642'),
        ('post', '0003_auto_20190826_2126'),
    ]

    operations = [
    ]
